# The app is hosted on VPS server. So basically we SSH into it and run the deploy script (git pull etc.)
name: Deploy Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to Server via SSH and run deploy script to deploy
      - name: Deploy to production server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.HOST_IP }}
          username: ${{ vars.HOST_USER }}
          key: ${{ secrets.MY_PRIVATE_KEY}}
          script: |
            #!/usr/bin/env bash
            set -e
            cd htdocs/tawin.my

            # ignore local changes
            git reset --hard
            git clean -fd

            git pull

            composer install
            npm install

            php artisan migrate

            # Clear cache & optimize
            php artisan icons:clear
            php artisan optimize:clear
            php artisan filament:optimize-clear

            php artisan icons:cache
            php artisan optimize
            php artisan filament:optimize

            npm run build
